from .vr180_stereo_tools import NODE_CLASS_MAPPINGS as VR_MAP, NODE_DISPLAY_NAME_MAPPINGS as VR_NAMES
from .muffins_offset_node import NODE_CLASS_MAPPINGS as MUFF_MAP, NODE_DISPLAY_NAME_MAPPINGS as MUFF_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(VR_MAP)
NODE_CLASS_MAPPINGS.update(MUFF_MAP)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(VR_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(MUFF_NAMES)

